Update github workflows for latest action versions
Specifically because of:

Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

Notice: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

Co-Authored-By: Claude Sonnet 4.6 <noreply@anthropic.com>